#! /usr/bin/php
<?php
require_once 'vendor/autoload.php';

use Codad5\Classcentral\Scraper;
use Stichoza\GoogleTranslate\GoogleTranslate;

$tr = new GoogleTranslate('en'); // Translates into English
$tr->setTarget('hi'); // Translate to Georgian

$man = Scraper::scrapeFromUrl("https://www.classcentral.com/", 1, function(&$main_html, $url){
    $html = $main_html;
    $html = preg_replace('/<script\b[^>]*>.*?<\/script>/is', '', $html);
    $html = preg_replace('/<style\b[^>]*>.*?<\/style>/is', '', $html);
    $matches = array();
    preg_match_all('/>([^<]*)</', $html, $matches);
    echo "begin translation for $url \n";
    $new_arr = [];
    global $tr;
    echo count($matches[1])."\n";
    $filtered_matches = array_values(array_unique($matches[1]));
    echo count($filtered_matches)."\n";
    $test_string = implode("==$",$filtered_matches);
    try {
        $use = $test_string;
        if(strlen($use) > 150) {

        }
        $test_string = $tr->translate($test_string);
        echo "translated test_string \n";
        $test_array = explode("==$", $test_string);
        var_dump($test_array);
        for ($i = 0; $i < count($filtered_matches); $i++) {
            if (empty(trim($filtered_matches[$i]))) continue;
            $new_arr[] = trim($filtered_matches[$i]);
            $html = str_replace(trim($filtered_matches[$i]), $test_array[$i], $main_html);
        }
    } catch (\Throwable $th) {
        //throw $th;
        echo $th->getMessage();
        return $main_html = $html;
    }
    var_dump($filtered_matches);
    $textNodes = $new_arr;
    return $main_html = $html;
});
