#! /usr/bin/php
<?php
require_once 'vendor/autoload.php';

use Codad5\Classcentral\Scraper;
use Stichoza\GoogleTranslate\GoogleTranslate;



function translate($string , $target)
{
    $tr = new GoogleTranslate('en'); // Translates from englush
    $tr->setTarget($target); 
    // var_dump($string);
    $string_array = splitString($string);
    $translated_array = []; 
    try{
        for ($i=0; $i < count($string_array); $i++) {
            // echo $i;
            $translated_array[] = $tr->translate($string_array[$i]);
        }
    }catch(\Throwable $th){
        echo $th->getMessage();
    }
    return implode($translated_array);
}

function splitString($str) {
    $result = array();
    $words = preg_split('/\s+/', $str, -1, PREG_SPLIT_NO_EMPTY);
    $len = count($words);
    $start = 0;
    while ($start < $len) {
        $end = $start + 100;
        $length = 0;
        for ($i = $start; $i < $end && $i < $len; $i++) {
            $word_length = strlen($words[$i]) + 1; // add 1 for the space character
            if ($length + $word_length > 110) {
                $end = $i;
                break;
            }
            $length += $word_length;
        }
        $result[] = implode(' ', array_slice($words, $start, $end - $start));
        $start = $end;
    }
    // var_dump($result);
    return $result;
}




$man = Scraper::scrapeFromUrl("https://www.classcentral.com/", 1, function(&$html, $url){
    $c_html = $html;
    $c_html = preg_replace('/<script\b[^>]*>.*?<\/script>/is', '', $c_html);
    $c_html = preg_replace('/<style\b[^>]*>.*?<\/style>/is', '', $c_html);
    $matches = array();
    preg_match_all('/>([^<]*)</', $c_html, $matches);
    echo "begin translation for $url \n";
    $new_arr = [];
    $filtered_matches = array_filter($matches[1], 'trim');
    $filtered_matches = array_values(array_unique($filtered_matches));
    $test_string = implode(" ==$ ",$filtered_matches);
    try {
        echo "translating test_string \n";
        $test_string = translate($test_string, 'hi');
        $test_array = explode("==$", $test_string);
        var_dump($test_array);
        echo "translated test_string ". trim($filtered_matches[12]) ." \n";
        for ($i = 0; $i < count($filtered_matches); $i++) {
            if (empty(trim($filtered_matches[$i]))) continue;
            $text = $test_array[$i] ?? $filtered_matches[$i];
            echo strpos($html, trim($filtered_matches[$i])) > 0 ? "Yes" : "false";
            echo PHP_EOL;
            $new_arr[] = $text;
            $html = str_replace(trim($filtered_matches[$i]), $text, $html);
            pre
            // $html = $c_html;
            if ( $i <= 2) echo $text;
            echo "IN c_html ". (strpos($c_html, $text) > 0 ? "Yes" : "false")."";
            echo PHP_EOL;
            echo "IN c_html 2 ". (strpos($c_html, trim($filtered_matches[$i])) > 0 ? "Yes" : "false")."";
            echo PHP_EOL;
        }
        // $c_html = "MEn are at  times bold";
        // $c_html = str_replace("times", "ईमेल", $c_html);
    } catch (\Throwable $th) {
        //throw $th;
        echo $th->getMessage();
    }
    // var_dump($filtered_matches);
    // $html = $c_html;
    // var_dump($c_html);
    $textNodes = $new_arr;
    // $html = "men";
    return $html;
});
